language: python

matrix:
  include:
    - language: generic
      os: osx
      osx_image: beta-xcode6.3

python:
  - 2.7

install:
  - sudo bash -c 'python2.7 <(curl https://bootstrap.pypa.io/get-pip.py)'
  - sudo pip install tox

script:
  - tox
